### PR TITLE
Simplify.

### PR DESCRIPTION
**Pull request by felipeeflores**
Check this out and tell me if that's what you're trying to do...

### CODE REVIEW

**Comment by wjlow** [comment]
Looks good to merge 👍

**Comment by felipeeflores** [comment]
If there were more errors to validate we could pattern match instead of map over the result...

**Comment by mateusz-myob** [comment]
@felipeeflores You missed the point here. The purpose of this repo is to demonstrate stacking `Future` and `Xor` using `XorT`. Have a read here: http://eed3si9n.com/herding-cats/stacking-future-and-either.html

**Comment by mateusz-myob** [comment]
Actually, the main goal of this repo was to show that IntelliJ incorrectly displays errors. It so happens when using `XorT`. Please vote: https://youtrack.jetbrains.com/issue/IDEA-162150 :)

**Comment by felipeeflores** [comment]
Ok sorry my bad, 
Could you make a change to try and understand the problem.
So you have something that gives you back a future of an Either?

**Comment by felipeeflores** [comment]
My Intellij wasn't complaining. I think...

**Comment by obszczymucha** [comment]
@felipeeflores Thanks Felipe! I'll probably just delete the repo once JetBrains fix the issue.

**Pull request closed without merging**
